var main = document.createElement("main");
main.className = "profile";
document.body.appendChild(main);

    var section = document.createElement("section");
    section.className = "section main-section section_black";
    main.appendChild(section);

        var article = document.createElement("article");
        article.className = "main-article main-article_white";
        section.appendChild(article);
            var h1 = document.createElement("h1");
            h1.className = "main-article__title";
            var textH1 = document.createTextNode("Григорий Селезнев");
            h1.appendChild(textH1);
            article.appendChild(h1);
        var ul = document.createElement("ul");
        ul.className = "main-article__list"; 
            var li0 = document.createElement("li");
            li0.className = "main-article__item";
            var textLi0 = document.createTextNode("Developer");
            li0.appendChild(textLi0);
            var li1 = document.createElement("li");
            li1.className = "main-article__item";
            var textLi1 = document.createTextNode("Developer");
            li1.appendChild(textLi1);
            var li2 = document.createElement("li");
            li2.className = "main-article__item";
            var textLi2 = document.createTextNode("Developer");
            li2.appendChild(textLi2);
            var li3 = document.createElement("li");
            li3.className = "main-article__item";
            var textLi3 = document.createTextNode("Developer");
            li3.appendChild(textLi3);
            ul.appendChild(li0);
            ul.appendChild(li1);
            ul.appendChild(li2);
            ul.appendChild(li3);
        article.appendChild(ul);
        var img = document.createElement("img");
        img.className = "section__img";
        img.src = "img/me.png";
        section.appendChild(img);

    var section = document.createElement("section");
    section.className = "section biography section_white";
    main.appendChild(section);

        var article = document.createElement("article");
        article.className = "article_black";
        section.appendChild(article);
            var h2 = document.createElement("h2");
            h2.className = "biography__title";
            var textH2 = document.createTextNode("Биография");
            h2.appendChild(textH2);
            article.appendChild(h2);
            var p0 = document.createElement("p");
            p0.className = "biography__title";
            var textP0 = document.createTextNode("Я");
            p0.appendChild(textP0);
            var p1 = document.createElement("p");
            p1.className = "biography__title";
            var textP1 = document.createTextNode("1989");
            p1.appendChild(textP1);
            var p2 = document.createElement("p");
            p2.className = "biography__title";
            var textP2 = document.createTextNode("2000");
            p2.appendChild(textP2);
            var p3 = document.createElement("p");
            p3.className = "biography__title";
            var textP3 = document.createTextNode("2003");
            p3.appendChild(textP3);
            var p4 = document.createElement("p");
            p4.className = "biography__title";
            var textP4 = document.createTextNode("2004");
            p4.appendChild(textP4);
            var p5 = document.createElement("p");
            p5.className = "biography__title";
            var textP5 = document.createTextNode("2012");
            p5.appendChild(textP5);
            article.appendChild(p0);
            article.appendChild(p1);
            article.appendChild(p2);
            article.appendChild(p3);
            article.appendChild(p4);
            article.appendChild(p5);
            var img = document.createElement("img");
            img.className = "biography__img";
            img.src = "img/me1.png";
            section.appendChild(img);

    var section = document.createElement("section");
    section.className = "section section_white";
    main.appendChild(section);

        var h2 = document.createElement("h2");
        h2.className = "section__title";
        var textH2 = document.createTextNode("Мой опыт");
        h2.appendChild(textH2);
        section.appendChild(h2);
        var article = document.createElement("article");
        article.className = "article_black";
        section.appendChild(article);
            var div = document.createElement("div");
            div.className = "experience";
            article.appendChild(div);
                var ul = document.createElement("ul");
                ul.className = "experience__list";
                div.appendChild(ul);
                var li0 = document.createElement("li");
                li0.className = "experience__item";
                var textLi0 = document.createTextNode("Установка и настройка ОС симейства Microsoft Windows");
                li0.appendChild(textLi0);
                var li1 = document.createElement("li");
                li1.className = "experience__item";
                var textLi1 = document.createTextNode("Создание и настройка локальных сетей");
                li1.appendChild(textLi1);
                var li2 = document.createElement("li");
                li2.className = "experience__item";
                var textLi2 = document.createTextNode("Установка и настройка видеонаблюдения");
                li2.appendChild(textLi2);
                ul.appendChild(li0);
                ul.appendChild(li1);
                ul.appendChild(li2);
                var ul = document.createElement("ul");
                ul.className = "experience__list";
                div.appendChild(ul);
                var li0 = document.createElement("li");
                li0.className = "experience__item";
                var textLi0 = document.createTextNode("Обслуживаание переферийного оборудования");
                li0.appendChild(textLi0);
                var li1 = document.createElement("li");
                li1.className = "experience__item";
                var textLi1 = document.createTextNode("Ремонот ПК и ноутбуков");
                li1.appendChild(textLi1);
                var li2 = document.createElement("li");
                li2.className = "experience__item";
                var textLi2 = document.createTextNode("Ремонт мобильных телефонов");
                li2.appendChild(textLi2);
                ul.appendChild(li0);
                ul.appendChild(li1);
                ul.appendChild(li2);
            
            // var newUl = document.getElementsByClassName("experience");
            // var list = 
            
            // var clone = list.cloneNode(true);
            // clone.children[0].innerHTML = "Обслуживаание переферийного оборудования";
            // clone.children[1].innerHTML = "Ремонот ПК и ноутбуков";
            // clone.children[2].innerHTML = "Ремонт мобильных телефонов";
            // div.appendChild(clone);

            // var clone = ul.cloneNode(true);
            // clone.children[0].in
            // div.appendChild(clone);

    var section = document.createElement("section");
    section.className = "section section_white";
    main.appendChild(section);

        var h2 = document.createElement("h2");
        h2.className = "section__title";
        var textH2 = document.createTextNode("Мои увлечения");
        h2.appendChild(textH2);
        section.appendChild(h2);
        var article = document.createElement("article");
        article.className = "article_black";
        section.appendChild(article);
            var div = document.createElement("div");
            div.className = "hobbies";
            article.appendChild(div);
                var img = document.createElement("img");
                img.className = "section__img";
                img.src = "img/electronics.png";
                div.appendChild(img);
                    var p0 = document.createElement("p");
                    p0.className = "hobbies__item";
                    var textP0 = document.createTextNode("Электроника");
                    p0.appendChild(textP0);
                    div.appendChild(p0);
                var img1 = document.createElement("img");
                img1.className = "section__img";
                img1.src = "img/sport.png";
                div.appendChild(img1);
                    var p1 = document.createElement("p");
                    p1.className = "hobbies__item";
                    var textP1 = document.createTextNode("Спорт");
                    p1.appendChild(textP1);
                    div.appendChild(p1);
            var div = document.createElement("div");
            div.className = "hobbies";
            article.appendChild(div);
                var img = document.createElement("img");
                img.className = "section__img";
                img.src = "img/electronics.png";
                div.appendChild(img);
                    var p0 = document.createElement("p");
                    p0.className = "hobbies__item";
                    var textP0 = document.createTextNode("Путишествия");
                    p0.appendChild(textP0);
                    div.appendChild(p0);
                var img1 = document.createElement("img");
                img1.className = "section__img";
                img1.src = "img/sport.png";
                div.appendChild(img1);
                    var p1 = document.createElement("p");
                    p1.className = "hobbies__item";
                    var textP1 = document.createTextNode("Хобби");
                    p1.appendChild(textP1);
                    div.appendChild(p1);

var footer = document.createElement("footer");
footer.className = "footer";
document.body.appendChild(footer);

    var section = document.createElement("section");
    section.className = "section section_black";
    footer.appendChild(section);

    var h1 = document.createElement("h1");
    h1.className = "footer__title";
    var textH1 = document.createTextNode("Контакты");
    h1.appendChild(textH1);
    section.appendChild(h1);
    var article = document.createElement("article");
    article.className = "footer-contact";
    section.appendChild(article);
        var div = document.createElement("div");
        div.className = "footer-form";
        article.appendChild(div);
            var form = document.createElement("form");
            form.className = "form";
            div.appendChild(form);
                var nameInput = document.createElement("input");
                nameInput.className = "footer-form__field";
                nameInput.type = "text";
                nameInput.name = "name";
                nameInput.placeholder = "Имя:";
                form.appendChild(nameInput);
                var emailInput = document.createElement("input");
                emailInput.className = "footer-form__field";
                emailInput.type = "text";
                emailInput.name = "email";
                emailInput.placeholder = "email:";
                form.appendChild(emailInput);
                var mesTextarea = document.createElement("textarea");
                mesTextarea.className = "footer-form__item";
                mesTextarea.name = "message";
                mesTextarea.cols = "54";
                mesTextarea.rows = "5";
                mesTextarea.placeholder = "Текст:";
                form.appendChild(mesTextarea);
                var buttonInput = document.createElement("input");
                buttonInput.className = "footer-form__button";
                buttonInput.type = "submit";
                buttonInput.value = "Отправить";
                form.appendChild(buttonInput);
        var div = document.createElement("div");
        div.className = "footer_white";
        article.appendChild(div);
            var footerP0 = document.createElement("p");
            footerP0.className = "contact__item";
                var footerImg0 = document.createElement("img");
                footerImg0.className = "footer__img";
                footerImg0.src = "img/emailicon.png";
                footerImg0.alt = "email: ";
                var footerSpan0 = document.createElement("span");
                var textSpan0 = document.createTextNode("sgp3982@gmail.com");
                footerSpan0.appendChild(textSpan0);
            div.appendChild(footerP0);
            div.appendChild(footerImg0);
            div.appendChild(footerSpan0);    
            var footerP1 = document.createElement("p");
            footerP1.className = "contact__item";
                var footerImg1 = document.createElement("img");
                footerImg1.className = "footer__img";
                footerImg1.src = "img/emailicon.png";
                footerImg1.alt = "phone: ";
                var footerSpan1 = document.createElement("span");
                var textSpan1 = document.createTextNode("+38(050)685-0218");
                footerSpan1.appendChild(textSpan1);
            div.appendChild(footerP1);
            div.appendChild(footerImg1);
            div.appendChild(footerSpan1);    

// var profilediv = document.getElementsByClassName("profile");
// var mainH1 = document.createElement("h1");
// mainH1.innerHTML = "sdfgasgf";
// profilediv.append("mainH1");





