document.writeln(" <main class=\"profile\"> "); 
document.writeln("         <section class=\"section main-section section_black\"> "); 
document.writeln("             <article class=\"main-article main-article_white\"> "); 
document.writeln("                 <h1 class=\"main-article__title\">Григорий Селезнев</h1> "); 
document.writeln("                 <ul class=\"main-article__list\"> "); 
document.writeln("                     <li class=\"main-article__item\">Системный администратор</li> "); 
document.writeln("                     <li class=\"main-article__item\">Ремонт ПК, ноутбуков, смартфонов и т.д.</li> "); 
document.writeln("                     <li class=\"main-article__item\">Быстро, надежно, качественно)))</li> "); 
document.writeln("                     <li class=\"main-article__item\">email: sgp3982@gmail.com</li> "); 
document.writeln("                 </ul> "); 
document.writeln("             </article> "); 
document.writeln("             <img class=\"section__img\" src=\"img/me.png\" alt=\"Я\"> "); 
document.writeln("         </section> "); 
document.writeln("         <section class=\"section biography section_white\"> "); 
document.writeln("             <article class=\"article_black\"> "); 
document.writeln("                 <h2 class=\"biography__title\">Краткая автобиографиия</h2> "); 
document.writeln("                     <p class=\"biography__item\"> Я, Селезнев Григорий Петрович, родился в 1982 году в пгт. Новоайдар, Луганской области.</p> "); 
document.writeln("                     <p class=\"biography__item\"> В 1989 г. пошел в первый класс Новоайдарской средней школы №1. Во время обучения в школе увлекался спортом, занимал призовые места в районе.</p>  "); 
document.writeln("                     <p class=\"biography__item\"> В 2000 г. получил аттестат о среднем образовании. Осенью поступил в  Луганский кооперативный колледж на факультет \"программирования\".</p> "); 
document.writeln("                     <p class=\"biography__item\"> В 2003 г. получил диплом с отличием по специальности: \"Техник - программист\". </p> "); 
document.writeln("                     <p class=\"biography__item\"> В 2004 г. Устроился на работу ОАО \"ОЩАДБАНК\" на должность: \"ведущий инженер отдела АСУ\". Попал под сокращение в 2011г.</p> "); 
document.writeln("                     <p class=\"biography__item\"> В 2012 г. Устроился в ООО \"Айдарский пекарь\" на должности: \"системный администратор\", где и работаю на данный момент.</p> "); 
document.writeln("             </article> "); 
document.writeln("             <img class=\"biography__img\" src=\"img/me1.png\" alt=\"Я\"> "); 
document.writeln("         </section> "); 
document.writeln("         <section class=\"section section_white\">     "); 
document.writeln("             <h2 class=\"section__title\">Мой опыт</h2> "); 
document.writeln("                 <article class=\"article_black\"> "); 
document.writeln("                     <div class=\"experience\"> "); 
document.writeln("                         <ul class=\"experience__list\"> "); 
document.writeln("                             <li class=\"experience__item\">Установка и настройка ОС симейства Microsoft Windows</li> "); 
document.writeln("                             <li class=\"experience__item\">Создание и настройка локальных сетей</li> "); 
document.writeln("                             <li class=\"experience__item\">Установка и настройка видеонаблюдения</li> "); 
document.writeln("                         </ul> "); 
document.writeln("                         <ul class=\"experience__list\"> "); 
document.writeln("                             <li class=\"experience__item\">Обслуживаание переферийного оборудования</li> "); 
document.writeln("                             <li class=\"experience__item\">Ремонот ПК и ноутбуков</li> "); 
document.writeln("                             <li class=\"experience__item\">Ремонт мобильных телефонов</li> "); 
document.writeln("                         </ul> "); 
document.writeln("                     </div> "); 
document.writeln("                 </article> "); 
document.writeln("         </section> "); 
document.writeln("         <section class=\"section section_white\"> "); 
document.writeln("             <h2 class=\"section__title\">Мои увлечения</h2> "); 
document.writeln("             <article class=\"article_black\"> "); 
document.writeln("                 <div class=\"hobbies\"> "); 
document.writeln("                     <img class=\"section__img\" src=\"img/electronics.png\" alt=\"Я\"> "); 
document.writeln("                     <p class=\"hobbies__item\">С детства увлекаюсь электроникой и ремонтом устройств и поэтому Я люблю свою работу. Интернет сделал доступным  "); 
document.writeln("                         практически все книги, картины, знания, путешествия и людей. Столько информации, что за всю жизнь не прочитаешь.</p> "); 
document.writeln("                     <img class=\"section__img\" src=\"img/sport.png\" alt=\"Я\"> "); 
document.writeln("                     <p class=\"hobbies__item\">Я люблю спорт. Это здоровье, хорошее настроение, нормализация сна, способ противостоять хроническому утомлению,  "); 
document.writeln("                         повысить стрессоустойчивость, увеличить запас жизненной энергии и поддерживать прекрасное самочувствие.</p> "); 
document.writeln("                 </div> "); 
document.writeln("                 <div class=\"hobbies\"> "); 
document.writeln("                     <img class=\"section__img\" src=\"img/turizm.png\" alt=\"Я\"> "); 
document.writeln("                     <p class=\"hobbies__item\">Я люблю путишествовать. В путешествиях просыпается любовь и жажда к жизни, можно пробовать что-то новое каждый день, "); 
document.writeln("                         можно встретить множество «своих» людей, которые оставят большой отпечаток и вдохновят на что-то большее. Путешествия дарят ощущение полной  "); 
document.writeln("                         свободы, расширяют представления о мире и насыщают душу.</p> "); 
document.writeln("                     <img class=\"section__img\" src=\"img/hunting.png\" alt=\"Я\"> "); 
document.writeln("                     <p class=\"hobbies__item\">Я люблю рыбалку потому что она помогает мне по настоящему отдохнуть, подумать о чем то прекрасном. Конечно никто и не  "); 
document.writeln("                         поспорит, что время проведенное на природе - это море эмоций. Охота и рыбалка всегда были в тренде как у молодежи, так и у поколения по старше</p>  "); 
document.writeln("                 </div> "); 
document.writeln("             </article> "); 
document.writeln("         </section> "); 
document.writeln("     </main> "); 
document.writeln("     <footer class=\"footer\"> "); 
document.writeln("         <section class=\"section section_black\"> "); 
document.writeln("             <h1 class=\"footer__title\">Контакты</h1> "); 
document.writeln("             <article class=\"footer-contact\"> "); 
document.writeln("                 <div id=\"footer-form\"> "); 
document.writeln("                 <form class=\"form\"> "); 
document.writeln("                     <input class=\"footer-form__field\" type=\"text\" name=\"name\" placeholder=\"Имя:\" required/> "); 
document.writeln("                     <input class=\"footer-form__field\" type=\"text\" name=\"email\" placeholder=\"Email:\" required/> "); 
document.writeln("                     <textarea class=\"footer-form__item\" name=\"message\" cols=\"54\" rows=\"5\" placeholder=\"Текст:\" required></textarea> "); 
document.writeln("                     <input class=\"footer-form__button\" type=\"submit\" value=\"Отправить\"/> "); 
document.writeln("                 </form> "); 
document.writeln("                 </div> "); 
document.writeln("                 <div class=\"footer_white\"> "); 
document.writeln("                     <p class=\"contact__item\"><img class=\"footer__img\" src=\"img/emailicon.png\" alt=\"email\"><span>sgp3982@gmail.com</span></p> "); 
document.writeln("                     <p class=\"contact__item\"><img class=\"footer__img\" src=\"img/phoneicon.png\" alt=\"fone\"><span>+38(050)685-0218</span</p> "); 
document.writeln("                 </div> "); 
document.writeln("             </article> "); 
document.writeln("         </section> "); 
document.writeln("     </footer> ");