import "./scss/main.scss";
var main = document.createElement("main");
main.className = "profile";
document.body.appendChild(main);

    var mainSection = document.createElement("section");
    mainSection.className = "section main-section section_black";
    main.appendChild(mainSection);

        var mainArticle = document.createElement("article");
        mainArticle.className = "main-article main-article_white";
        mainSection.appendChild(mainArticle);
            var mainH1 = document.createElement("h1");
            mainH1.className = "main-article__title";
            var textH1 = document.createTextNode("Григорий Селезнев");
            mainH1.appendChild(textH1);
            mainArticle.appendChild(mainH1);
        var mainUl = document.createElement("ul");
        mainUl.className = "main-article__list"; 
            var li0 = document.createElement("li");
            li0.className = "main-article__item";
            var textLi0 = document.createTextNode("sgp3982@gmail.com");
            li0.appendChild(textLi0);
            var li1 = document.createElement("li");
            li1.className = "main-article__item";
            var textLi1 = document.createTextNode("sgp3982@gmail.com");
            li1.appendChild(textLi1);
            var li2 = document.createElement("li");
            li2.className = "main-article__item";
            var textLi2 = document.createTextNode("sgp3982@gmail.com");
            li2.appendChild(textLi2);
            var li3 = document.createElement("li");
            li3.className = "main-article__item";
            var textLi3 = document.createTextNode("sgp3982@gmail.com");
            li3.appendChild(textLi3);
            mainUl.appendChild(li0);
            mainUl.appendChild(li1);
            mainUl.appendChild(li2);
            mainUl.appendChild(li3);
            mainArticle.appendChild(mainUl);
        var mainImg = document.createElement("img");
        mainImg.className = "section__img";
        mainImg.src = "../src/img/me.png";
        mainSection.appendChild(mainImg);

    var graphSection = document.createElement("section");
    graphSection.className = "section biography section_white";
    main.appendChild(graphSection);

        var graphArticle = document.createElement("article");
        graphArticle.className = "article_black";
        graphSection.appendChild(graphArticle);
            var graphH2 = document.createElement("h2");
            graphH2.className = "biography__title";
            var textH2 = document.createTextNode("Биография");
            graphH2.appendChild(textH2);
            graphArticle.appendChild(graphH2);
            var graphP0 = document.createElement("p");
            graphP0.className = "biography__title";
            var textP0 = document.createTextNode("Я");
            graphP0.appendChild(textP0);
            var graphP1 = document.createElement("p");
            graphP1.className = "biography__title";
            var textP1 = document.createTextNode("1989 текст текст текст текст текст текст текст");
            graphP1.appendChild(textP1);
            var graphP2 = document.createElement("p");
            graphP2.className = "biography__title";
            var textP2 = document.createTextNode("2000 текст текст текст текст текст текст текст текст текст текст ");
            graphP2.appendChild(textP2);
            var graphP3 = document.createElement("p");
            graphP3.className = "biography__title";
            var textP3 = document.createTextNode("2003  текст текст текст текст текст текст ");
            graphP3.appendChild(textP3);
            var graphP4 = document.createElement("p");
            graphP4.className = "biography__title";
            var textP4 = document.createTextNode("2004 текст ттекст текст текст текст текст текст текст ");
            graphP4.appendChild(textP4);
            var graphP5 = document.createElement("p");
            graphP5.className = "biography__title";
            var textP5 = document.createTextNode("2012 текст тетекст текст текст текст текст текст текст текст текст текст ");
            graphP5.appendChild(textP5);
            graphArticle.appendChild(graphP0);
            graphArticle.appendChild(graphP1);
            graphArticle.appendChild(graphP2);
            graphArticle.appendChild(graphP3);
            graphArticle.appendChild(graphP4);
            graphArticle.appendChild(graphP5);
            var graphImg = document.createElement("img");
            graphImg.className = "biography__img";
            graphImg.src = "../src/img/me1.png";
            graphSection.appendChild(graphImg);

    var experSection = document.createElement("section");
    experSection.className = "section section_white";
    main.appendChild(experSection);

        var experH2 = document.createElement("h2");
        experH2.className = "section__title";
        var textH2 = document.createTextNode("Мой опыт");
        experH2.appendChild(textH2);
        experSection.appendChild(experH2);
        var experArticle = document.createElement("article");
        experArticle.className = "article_black";
        experSection.appendChild(experArticle);
            var experDiv = document.createElement("div");
            experDiv.className = "experience";
            experArticle.appendChild(experDiv);
                var experUl = document.createElement("ul");
                experUl.className = "experience__list";
                experDiv.appendChild(experUl);
                    var li0 = document.createElement("li");
                    li0.className = "experience__item";
                    var textLi0 = document.createTextNode("текст текст текст текст текст текст текст текст ");
                    li0.appendChild(textLi0);
                    var li1 = document.createElement("li");
                    li1.className = "experience__item";
                    var textLi1 = document.createTextNode("текст текст текст текст текст текст текст текст ");
                    li1.appendChild(textLi1);
                    var li2 = document.createElement("li");
                    li2.className = "experience__item";
                    var textLi2 = document.createTextNode("текст текст текст текст текст текст текст текст ");
                    li2.appendChild(textLi2);
                experUl.appendChild(li0);
                experUl.appendChild(li1);
                experUl.appendChild(li2);
                var experUl1 = document.createElement("ul");
                experUl1.className = "experience__list";
                experDiv.appendChild(experUl1);
                    var li0 = document.createElement("li");
                    li0.className = "experience__item";
                    var textLi0 = document.createTextNode("текст текст текст текст текст текст текст текст ");
                    li0.appendChild(textLi0);
                    var li1 = document.createElement("li");
                    li1.className = "experience__item";
                    var textLi1 = document.createTextNode("текст текст текст текст текст текст текст текст ");
                    li1.appendChild(textLi1);
                    var li2 = document.createElement("li");
                    li2.className = "experience__item";
                    var textLi2 = document.createTextNode("текст текст текст текст текст текст текст текст ");
                    li2.appendChild(textLi2);
                experUl1.appendChild(li0);
                experUl1.appendChild(li1);
                experUl1.appendChild(li2);
            
    var hobbSection = document.createElement("section");
    hobbSection.className = "section section_white";
    main.appendChild(hobbSection);

        var hobbH2 = document.createElement("h2");
        hobbH2.className = "section__title";
        var textH2 = document.createTextNode("Мои увлечения");
        hobbH2.appendChild(textH2);
        hobbSection.appendChild(hobbH2);
        var hobbArticle = document.createElement("article");
        hobbArticle.className = "article_black";
        hobbSection.appendChild(hobbArticle);
            var hobbDiv0 = document.createElement("div");
            hobbDiv0.className = "hobbies";
            hobbArticle.appendChild(hobbDiv0);
                var hobbImg0 = document.createElement("img");
                hobbImg0.className = "section__img";
                hobbImg0.src = "../src/img/electronics.png";
                hobbDiv0.appendChild(hobbImg0);
                    var p0 = document.createElement("p");
                    p0.className = "hobbies__item";
                    var textP0 = document.createTextNode("Электроника  текст текст текст текст текст текст текст текст текст текст текст текст текст текст текст текст текст текст текст текст ");
                    p0.appendChild(textP0);
                    hobbDiv0.appendChild(p0);
                var hobbImg1 = document.createElement("img");
                hobbImg1.className = "section__img";
                hobbImg1.src = "../src/img/sport.png";
                hobbDiv0.appendChild(hobbImg1);
                    var p1 = document.createElement("p");
                    p1.className = "hobbies__item";
                    var textP1 = document.createTextNode("Спорт  текст текст текст текст текст текст текст текст текст текст текст текст текст текст текст текст текст текст текст текст текст ");
                    p1.appendChild(textP1);
                    hobbDiv0.appendChild(p1);
            var hobbDiv1 = document.createElement("div");
            hobbDiv1.className = "hobbies";
            hobbArticle.appendChild(hobbDiv1);
                var hobbImg0 = document.createElement("img");
                hobbImg0.className = "section__img";
                hobbImg0.src = "../src/img/electronics.png";
                hobbDiv1.appendChild(hobbImg0);
                    var p0 = document.createElement("p");
                    p0.className = "hobbies__item";
                    var textP0 = document.createTextNode("Путишествия  текст текст текст текст текст текст текст текст текст текст текст текст текст текст текст текст текст текст текст текст текст текст ");
                    p0.appendChild(textP0);
                    hobbDiv1.appendChild(p0);
                var hobbImg1 = document.createElement("img");
                hobbImg1.className = "section__img";
                hobbImg1.src = "../src/img/sport.png";
                hobbDiv1.appendChild(hobbImg1);
                    var p1 = document.createElement("p");
                    p1.className = "hobbies__item";
                    var textP1 = document.createTextNode("Хобби  текст текст текст текст текст текст текст текст текст текст текст текст текст текст текст текст текст текст текст текст текст текст ");
                    p1.appendChild(textP1);
                    hobbDiv1.appendChild(p1);

var footer = document.createElement("footer");
footer.className = "footer";
document.body.appendChild(footer);


    var section = document.createElement("section");
    section.className = "section section_black";
    footer.appendChild(section);

        var h1 = document.createElement("h1");
        h1.className = "footer__title";
        var textH1 = document.createTextNode("Контакты");
        h1.appendChild(textH1);
        section.appendChild(h1);
        var article = document.createElement("article");
        article.className = "footer-contact";
        section.appendChild(article);
            var div = document.createElement("div");
            div.className = "footer-form";
            article.appendChild(div);
                var form = document.createElement("form");
                form.className = "form";
                div.appendChild(form);
                    var nameInput = document.createElement("input");
                    nameInput.className = "footer-form__field";
                    nameInput.type = "text";
                    nameInput.name = "name";
                    nameInput.placeholder = "Имя:";
                    form.appendChild(nameInput);
                    var emailInput = document.createElement("input");
                    emailInput.className = "footer-form__field";
                    emailInput.type = "text";
                    emailInput.name = "email";
                    emailInput.placeholder = "email:";
                    form.appendChild(emailInput);
                    var mesTextarea = document.createElement("textarea");
                    mesTextarea.className = "footer-form__item";
                    mesTextarea.name = "message";
                    mesTextarea.cols = "54";
                    mesTextarea.rows = "5";
                    mesTextarea.placeholder = "Текст:";
                    form.appendChild(mesTextarea);
                    var buttonInput = document.createElement("input");
                    buttonInput.className = "footer-form__button";
                    buttonInput.type = "submit";
                    buttonInput.value = "Отправить";
                    form.appendChild(buttonInput);
            var div = document.createElement("div");
            div.className = "footer_white";
            article.appendChild(div);
                var footerP0 = document.createElement("p");
                footerP0.className = "contact__item";
                    var footerImg0 = document.createElement("img");
                    footerImg0.className = "footer__img";
                    footerImg0.src = "../src/img/emailicon.png";
                    footerImg0.alt = "email: ";
                    var footerSpan0 = document.createElement("span");
                    var textSpan0 = document.createTextNode("sgp3982@gmail.com");
                    footerSpan0.appendChild(textSpan0);
                div.appendChild(footerP0);
                div.appendChild(footerImg0);
                div.appendChild(footerSpan0);    
                var footerP1 = document.createElement("p");
                footerP1.className = "contact__item";
                    var footerImg1 = document.createElement("img");
                    footerImg1.className = "footer__img";
                    footerImg1.src = "../src/img/emailicon.png";
                    footerImg1.alt = "phone: ";
                    var footerSpan1 = document.createElement("span");
                    var textSpan1 = document.createTextNode("+38(050)685-0218");
                    footerSpan1.appendChild(textSpan1);
                div.appendChild(footerP1);
                div.appendChild(footerImg1);
                div.appendChild(footerSpan1);    